=== raswithavaddepally/Projects/XML Churning/PROJECT 2/reviews.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="REVIEW">
        <xs:annotation>
            <xs:documentation>Comment describing your root element</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="REVIEWS" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="DVDTITLE"/>
                            <xs:element name="RATING">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="1"/>
                                        <xs:maxInclusive value="5"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="REVIEWER" minOccurs="0"/>
                            <xs:element name="REVIEWDATE" type="xs:date" minOccurs="0"/>
                            <xs:element name="LOCATION">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-zA-Z/' /']*[/,][/' /'][a-zA-Z]*"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="REVIEW"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== raswithavaddepally/Projects/XML Churning/PROJECT 2/reviews.xml
<?xml version="1.0" encoding="UTF-8"?>
<REVIEW xsi:noNamespaceSchemaLocation="reviews.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<REVIEWS>
		<DVDTITLE>A.I. Artificial Intelligence</DVDTITLE>
		<RATING>5</RATING>
		<REVIEWER>Andrew</REVIEWER>
		<REVIEWDATE>2002-01-31</REVIEWDATE>
		<LOCATION>San Diego, CA</LOCATION>
		<REVIEW>Amazing, visually stunning and thought-inspiring</REVIEW>
	</REVIEWS>
	<REVIEWS>
		<DVDTITLE>A.I. Artificial Intelligence</DVDTITLE>
		<RATING>1</RATING>
		<REVIEWER>Chris</REVIEWER>
		<REVIEWDATE>2002-01-09</REVIEWDATE>
		<LOCATION>Deerfield, IL</LOCATION>
		<REVIEW>What a JOKE!</REVIEW>
	</REVIEWS>
	<REVIEWS>
		<DVDTITLE>Beauty and the Beast</DVDTITLE>
		<RATING>5</RATING>
		<REVIEWER>George</REVIEWER>
		<REVIEWDATE>2002-02-27</REVIEWDATE>
		<LOCATION>Baltimore, MD</LOCATION>
		<REVIEW>A Disney film that deserves its Best Picture Nomination.</REVIEW>
	</REVIEWS>
	<REVIEWS>
		<DVDTITLE>Beauty and the Beast</DVDTITLE>
		<RATING>2</RATING>
		<REVIEWER>Robert</REVIEWER>
		<REVIEWDATE>2002-03-19</REVIEWDATE>
		<LOCATION>LA, CA</LOCATION>
		<REVIEW>Disappointed.</REVIEW>
	</REVIEWS>
	<REVIEWS>
		<DVDTITLE>Disclosure</DVDTITLE>
		<RATING>1</RATING>
		<REVIEWER>George</REVIEWER>
		<REVIEWDATE>2002-03-03</REVIEWDATE>
		<LOCATION>Baltimore, MD</LOCATION>
		<REVIEW>This movie is insulting.</REVIEW>
	</REVIEWS>
	<REVIEWS>
		<DVDTITLE>Disclosure</DVDTITLE>
		<RATING>5</RATING>
		<REVIEWER>Matthew</REVIEWER>
		<REVIEWDATE>2002-11-03</REVIEWDATE>
		<LOCATION>Topsail Beach, NC</LOCATION>
		<REVIEW>An Excellent Adaptation.</REVIEW>
	</REVIEWS>
	<REVIEWS>
		<DVDTITLE>Ghost</DVDTITLE>
		<RATING>2</RATING>
		<REVIEWER>Alex</REVIEWER>
		<REVIEWDATE>2002-03-01</REVIEWDATE>
		<LOCATION>Chicago, IL</LOCATION>
		<REVIEW>A tremendous disappointment.</REVIEW>
	</REVIEWS>
	<REVIEWS>
		<DVDTITLE>Ghost</DVDTITLE>
		<RATING>5</RATING>
		<REVIEWER>Robert</REVIEWER>
		<REVIEWDATE>2002-03-13</REVIEWDATE>
		<LOCATION>LA, CA</LOCATION>
		<REVIEW>YOU'LL FALL IN LOVE WITH "GHOST"!</REVIEW>
	</REVIEWS>
	<REVIEWS>
		<DVDTITLE>Legally Blonde</DVDTITLE>
		<RATING>1</RATING>
		<REVIEWER>Jeremy</REVIEWER>
		<REVIEWDATE>2002-02-18</REVIEWDATE>
		<LOCATION>Buffalo, NY</LOCATION>
		<REVIEW>Looks Good Enough - Too Bad It Makes No Sense</REVIEW>
	</REVIEWS>
	<REVIEWS>
		<DVDTITLE>Legally Blonde</DVDTITLE>
		<RATING>4</RATING>
		<REVIEWER>Robert</REVIEWER>
		<REVIEWDATE>2002-01-11</REVIEWDATE>
		<LOCATION>LA, CA</LOCATION>
		<REVIEW>Alright DVD</REVIEW>
	</REVIEWS>
	<REVIEWS>
		<DVDTITLE>Moulin Rouge</DVDTITLE>
		<RATING>3</RATING>
		<REVIEWER>Angela</REVIEWER>
		<REVIEWDATE>2002-03-16</REVIEWDATE>
		<LOCATION>NYC, NY</LOCATION>
		<REVIEW>You have to watch it twice.,</REVIEW>
	</REVIEWS>
	<REVIEWS>
		<DVDTITLE>Moulin Rouge</DVDTITLE>
		<RATING>5</RATING>
		<REVIEWER>John</REVIEWER>
		<REVIEWDATE>2002-02-19</REVIEWDATE>
		<LOCATION>Houston, TX</LOCATION>
		<REVIEW>Love it or Hate it--it is a great film and an awesome DVD!,</REVIEW>
	</REVIEWS>
	<REVIEWS>
		<DVDTITLE>Moulin Rouge</DVDTITLE>
		<RATING>5</RATING>
		<REVIEWER>Robert</REVIEWER>
		<REVIEWDATE>2002-01-22</REVIEWDATE>
		<LOCATION>LA, CA</LOCATION>
		<REVIEW>Best movie of 2001 and a great DVD to own.</REVIEW>
	</REVIEWS>
	<REVIEWS>
		<DVDTITLE>Terminator 2 - Judgment Day</DVDTITLE>
		<RATING>5</RATING>
		<REVIEWER>Angela</REVIEWER>
		<REVIEWDATE>2002-02-28</REVIEWDATE>
		<LOCATION>NYC, NY</LOCATION>
		<REVIEW>Oh, boy. This is the best special edition DVD yet.</REVIEW>
	</REVIEWS>
	<REVIEWS>
		<DVDTITLE>Terminator 2 - Judgment Day</DVDTITLE>
		<RATING>4</RATING>
		<REVIEWER>Christine</REVIEWER>
		<REVIEWDATE>2002-01-14</REVIEWDATE>
		<LOCATION>El Paso, TX</LOCATION>
		<REVIEW>SciFi Winner</REVIEW>
	</REVIEWS>
	<REVIEWS>
		<DVDTITLE>Terminator 2 - Judgment Day</DVDTITLE>
		<RATING>4</RATING>
		<REVIEWER>Christine</REVIEWER>
		<REVIEWDATE>2002-01-14</REVIEWDATE>
		<LOCATION>El Paso, TX</LOCATION>
		<REVIEW>SciFi Winner</REVIEW>
	</REVIEWS>
	<REVIEWS>
		<DVDTITLE>The Matrix</DVDTITLE>
		<RATING>5</RATING>
		<REVIEWER>David</REVIEWER>
		<REVIEWDATE>2002-03-14</REVIEWDATE>
		<LOCATION>Palos Park, IL</LOCATION>
		<REVIEW>WITHOUT A DOUBT A MASTERPIECE OF A MOVIE</REVIEW>
	</REVIEWS>
	<REVIEWS>
		<DVDTITLE>The Matrix</DVDTITLE>
		<RATING>2</RATING>
		<REVIEWER>Eugene</REVIEWER>
		<REVIEWDATE>2002-01-25</REVIEWDATE>
		<LOCATION>Riverside, CA</LOCATION>
		<REVIEW>Great idea swiftly plumits downhill</REVIEW>
	</REVIEWS>
	<REVIEWS>
		<DVDTITLE>The Mummy Returns</DVDTITLE>
		<RATING>2</RATING>
		<REVIEWER>Eugene</REVIEWER>
		<REVIEWDATE>2002-01-02</REVIEWDATE>
		<LOCATION>Riverside, CA</LOCATION>
		<REVIEW>Indiana Jones Revisited</REVIEW>
	</REVIEWS>
	<REVIEWS>
		<DVDTITLE>The Mummy Returns</DVDTITLE>
		<RATING>1</RATING>
		<REVIEWER>Justine</REVIEWER>
		<REVIEWDATE>2002-03-12</REVIEWDATE>
		<LOCATION>San Francisco, CA</LOCATION>
		<REVIEW>You've got to be kidding me!!!</REVIEW>
	</REVIEWS>
	<REVIEWS>
		<DVDTITLE>The Mummy Returns</DVDTITLE>
		<RATING>5</RATING>
		<REVIEWER>Tom</REVIEWER>
		<REVIEWDATE>2002-02-12</REVIEWDATE>
		<LOCATION>La Habra, CA</LOCATION>
		<REVIEW>The Mummy - the best DVD you can buy</REVIEW>
	</REVIEWS>
	<REVIEWS>
		<DVDTITLE>Titanic</DVDTITLE>
		<RATING>5</RATING>
		<REVIEWER>Angela</REVIEWER>
		<REVIEWDATE>2002-03-06</REVIEWDATE>
		<LOCATION>NYC, NY</LOCATION>
		<REVIEW>The most triumphant romance film of all time</REVIEW>
	</REVIEWS>
	<REVIEWS>
		<DVDTITLE>Titanic</DVDTITLE>
		<RATING>2</RATING>
		<REVIEWER>Bill</REVIEWER>
		<REVIEWDATE>2002-01-28</REVIEWDATE>
		<LOCATION>Casper, WY</LOCATION>
		<REVIEW>Hollywood produces another sinking ship.</REVIEW>
	</REVIEWS>
</REVIEW>
